repos:
    - repo: https://github.com/pycqa/isort
      rev: 5.11.2
      hooks:
        - id: isort
          name: Python - isort
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: "v2.0.0"
      hooks:
          - id: autopep8
            name: Python - autopep8